# Generated by Django 5.0.2 on 2024-06-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('Dr. Jane Starfield', 'Dr. Jane Starfield'), ('John Doe', 'John Doe'), ('Mark Thompson', 'Mark Thompson'), ('Rachel Eco', 'Rachel Eco'), ('Dr. Emma Stone', 'Dr. Emma Stone'), (' Laura Peace', 'Laura Peace')], default='John Doe', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('History', 'History'), (' Environment', ' Environment'), ('Cooking', 'Cooking'), ('Programming', 'Programming'), ('Marketing', 'Marketing'), (' Health', ' Health')], default='History', max_length=30),
        ),
    ]
