# Generated by Django 5.0.2 on 2024-06-16 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_alter_post_author_alter_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='tag',
        ),
    ]
