# Generated by Django 5.0.2 on 2024-06-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_rename_tags_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('History', 'History'), (' Environment', ' Environment'), ('Cooking', 'Cooking'), ('Programming', 'Programming'), ('Marketing', 'Marketing'), (' Astronomy', ' Astronomy')], default='History', max_length=30),
        ),
    ]
