# Generated by Django 5.0.2 on 2024-06-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('Dr. Jane Starfield', 'Dr. Jane Starfield'), ('John Doe', 'John Doe'), ('Mark Thompson', 'Mark Thompson'), ('Rachel Eco', 'Rachel Eco'), ('Dr. Emma Stone', 'Dr. Emma Stone'), ('Laura Peace', 'Laura Peace')], default='John Doe', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('History', 'History'), ('Environment', 'Environment'), ('Cooking', 'Cooking'), ('Programming', 'Programming'), ('Marketing', 'Marketing'), ('Astronomy', 'Astronomy')], default='History', max_length=30),
        ),
    ]
